### ISSUE TITLE
data source comune?

### ISSUE THREAD

**Issue by marcogoldin** [Dataninja/j-r-p#1]
ciao a tutti, che dite ci diamo una sorgente comune di dati per fare il giochino?
io pensavo a qualche tabella da Wikipedia per non complicarsi troppo la vita (Istat le embedda in iframe se non sbaglio e non so se scrapare da lì sia un po' overkill, peccato).
Faccio un esempio tanto per rompere il ghiaccio: https://it.wikipedia.org/wiki/Leone_d%27oro_al_miglior_film 
si prende la tabella dei vincitori, la si pivota come vogliamo, non so ad esempio per nazionalità e le righe contenenti il numero di vittorie.
Qualche idea?

**Comment by jenkin** [comment]
Direi che va più che bene, ho [aggiornato il README](https://github.com/Dataninja/j-r-p/blob/master/README.md).
