### ISSUE TITLE
Conteggio credo errato

### ISSUE THREAD

**Issue by aborruso** [Dataninja/j-r-p#11]
Caro @pieroit Italia e Francia hanno vinto 11 leoni e non 10.

Credo tu non abbia considerato quegli anni con più di un vincitore.

Buona giornata

**Comment by aborruso** [comment]
Credo sia lo stesso per lo script in Julia di @marcogoldin

**Comment by jenkin** [comment]
Vedi issue #3

**Comment by jenkin** [comment]
Ho fatto il merge nella mia branch sulla master, ora le due soluzioni di python funzionano bene.
