### ISSUE TITLE
E se aggiungessimo anche bash e le utility Linux?

### ISSUE THREAD

**Issue by aborruso** [Dataninja/j-r-p#2]
Nel caso mi offro volontario :)

E quindi sarebbe j-r-p-l(inux) o j-r-p-b(ash)

**Comment by jenkin** [comment]
Se aggiungi la `b` finale ti tocca continuare la storia del titolo del README... 😄

**Comment by jenkin** [comment]
Ecco! https://github.com/Dataninja/j-r-p/commit/bdd93b599efe237d03ae2d13751468417f695b39
