### ISSUE TITLE
Gestire le produzioni transnazionali

### ISSUE THREAD

**Issue by jenkin** [Dataninja/j-r-p#3]
Alcuni film sono co-prodotti da più nazioni, per cui la pivot dovrebbe tenerne conto e conteggiare lo stesso film per ogni nazione coinvolta. [Esempio](https://github.com/Dataninja/j-r-p/blob/master/Python/paesi_vincitori.csv#L16).

**Comment by gvdr** [comment]
In R e` risolta, il problema esiste anche nella versione Julia.

**Comment by marcogoldin** [comment]
Vero, il problema rimane in Julia perché l'ho volutamente ignorato , con un po' di tempo a disposizione rimetterò mano al codice e vediamo di sistemare anche questo dettaglio.

**Comment by aborruso** [comment]
Appena trovo un momento di tempo in settimana, correggo anche io

**Comment by aborruso** [comment]
In `Bash` è solved

**Comment by marcogoldin** [comment]
solved anche in Julia, ricaricato codice.

**Comment by aborruso** [comment]
@marcogoldin nel grafico vedo 10 leoni per l'Italia, mentre dovrebbero essere 11

**Comment by marcogoldin** [comment]
E invece avete sbagliato tutti :P
nel 1959 l'Italia vince con 2 film parimerito, ma il leone di fatto assegnato/conquistato dal paese di produzione è uno. (poi se se ne contano 2 è una scelta "interpretativa" eh). Comunque il Leone d'Oro sarebbe uno solo assegnato a pari merito in teoria

**Comment by jenkin** [comment]
Dovrebbe far fede il grafico della stessa wikipedia, che riporta 11 leoni per l'Italia...

**Comment by marcogoldin** [comment]
vabbé corretto, per me rimane una scelta comunque giusto fare tutti uguale. 11 per L'Italia siano!

**Comment by jenkin** [comment]
Prova a proporre una modifica alla voce di Wikipedia, magari dopo aver cercato altre fonti in accordo con la tua interpretazione. Che dice per esempio il sito ufficiale?

**Comment by marcogoldin** [comment]
Ma no va benissimo, figurati. Sul sito ufficiale avevo ovviamente provato a guardare ma manca un elenco riassuntivo, poi se non sbaglio ti permette al massimo di andare indietro di un anno. Peccato ma ripeto va bene così per me :)
